#
# Copyright (C) 2026 by scriptwriter13
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

default_platform(:android)

platform :android do
  desc "Build Release APK for F-Droid"
  lane :build do
    gradle(task: "assembleRelease")
  end
end
